; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
src_dir = main

;[env:esp32doit-devkit-v1]
[env:esp32-c6-devkitc-1]
; FUTURE: [env:esp32c6-devkitc-1]

;platform = espressif32 @ 6.9.0
platform = espressif32 @ 6.13.0

;board = esp32doit-devkit-v1
board = esp32-c6-devkitc-1
; FUTURE: board = esp32c6-devkitc-1


;framework = arduino
framework = espidf

; Debug config
#build_type = debug


#debug_tool = esp-builtin
#upload_protocol = esp-builtin
#debug_speed = 5000
#debug_server =
#  /home/vladimir/.platformio/packages/tool-openocd-esp32-new/bin/openocd
#  -s /home/vladimir/.platformio/packages/tool-openocd-esp32-new/share/openocd/scripts
#  -f board/esp32c6-builtin.cfg
#  -c "adapter speed 1000"
#  -c "reset_config none"
#debug_init_cmds =
#  target extended-remote $DEBUG_PORT
#  $LOAD_CMDS
 # $INIT_BREAK


#upload_port = /dev/ttyACM1





build_unflags = -std=gnu++11
build_flags = -std=gnu++17
    -DCCACHE_ENABLE=1
    -DCONFIG_ESP_COREDUMP_ENABLE_TO_FLASH=1
    -DCONFIG_ESP_COREDUMP_DATA_FORMAT_BIN=1
    -Icomponents/croniot/src
    -Icomponents/croniot/src/network
    -Icomponents/croniot/src/Messages
    -Icomponents/croniot/src/Parameters
    -Icomponents/croniot/src/Sensors
    -Icomponents/croniot/src/Tasks


upload_speed = 6000000
monitor_speed = 115200
;build_type = release
;board_build.partitions = custompart.csv
board_build.partitions = partitions.csv
board_upload.flash_size = 16MB
board_build.filesystem = littlefs

monitor_filters = esp32_exception_decoder #For decoding exceptions


;platform_packages =
;    platformio/framework-arduinoespressif32@^3.20017.0 ;Used to be: 3.20016

;lib_deps =
;    symlink://../../croniot-iot #symlink = Changes made in source will affect this project
								#or alternatively you can add the library from: https://github.com/vladimir-ivanov-info/croniot-iot
;    bblanchon/ArduinoJson@^7.2.0
;	PubSubClient
;	WiFi
;	SPI
;	robtillaart/ADS1X15@^0.5.1
;	HTTPClient
;   WiFiClientSecure
;    Wire
;    EEPROM
;    FS
;    littlefs
;    marvinroger/AsyncMqttClient@^0.8.2



; Esta línea es la clave para proyectos ESP-IDF avanzados:
board_build.embed_txtfiles =
;build_src_dir = .
